version: '3.2'
services:
  movies:
    image: movies:v1
    ports:
      - "98:80"
    deploy:
      replicas: 3
    
  recharge:
    image: recharge:v1
    ports:
      - "99:80"
    deploy:
      replicas: 3  
        
 
     

