version: '3.2'
services:
  movies:
    image: movies:v1
    ports:
      - "87:80"
    
  recharge:
    image: train:v1
    ports:
      - "88:80"
        
  dth:
    image: dth:v1
    ports:
      - "89:80"
     

